id: AAFC24772
title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
type: translation
pechas:
- I0DA6682A
- I598095C1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:09:09.225517
  last_modified_at: 2023-01-04 12:09:09.225533
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I0DA6682A/FCF8: 4C15
  I598095C1/F7A1: 4C15
